Project/urls.py
from django.conf.urls.static import static
from django.urls import path,include
from django.conf import settings
from django.contrib import admin


urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('recipes.urls')),
    path('author/', include ('authors.urls'))
]

urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)
urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

recipes/urls.py
from django.urls import path  
from . import views

app_name="recipes"

urlpatterns = [
    path('', views.home , name="home"),
    path('recipes/search/', views.search, name = "search"),
    path('recipes/category/<int:id_category>/',views.category, name="category"),
    path('recipes/<int:id>/', views.recipe, name="recipes"),
    path('teste/',views.teste),
]

recipes/models.py
from django.contrib.auth.models import User
from django.db import models

# Created model recipes

class Category(models.Model):
    name = models.CharField(max_length=65)

    def __str__(self):
        return self.name
class RecipeModel(models.Model):
    category = models.ForeignKey(Category, on_delete=models.SET_NULL, null=True, blank=True, default=None,)
    author = models.ForeignKey(User, on_delete=models.SET_NULL, null=True)
    title = models.CharField(max_length=65)
    description = models.CharField(verbose_name="Descrição", max_length=165)
    slug = models.SlugField(unique=True)
    preparation_time = models.IntegerField(verbose_name="Tempo de prepro")
    preparation_time_unit =models.CharField(verbose_name="Preparação tempo de unidade", max_length=65)
    servings = models.CharField(verbose_name="Serve", max_length=3)
    servings_unit = models.CharField(verbose_name="serve Pessoas", max_length=65)
    preparation_step = models.CharField(verbose_name="Etapa de preparação", max_length=165)
    preparation_step_is_html = models.BooleanField(default="False")
    created_at = models.DateTimeField( auto_now_add=True)
    update_at = models.DateTimeField(auto_now=True)
    is_published = models.BooleanField( default=False )
    cover = models.ImageField(upload_to="recipes/cover/%Y/%m/%d/", null=True, blank=True, default=False)

    def __str__(self):
        return self.title
        """
    Purpose: 
    """
    
  # end def

recipes/views.py
import os
from django.db.models import Q
from django.shortcuts import render, get_list_or_404, get_object_or_404
from django.http import Http404, HttpResponse
from utils.recipes.factory import make_recipes
from utils.recipes.pagination import make_pagination
from .models import RecipeModel
from django.contrib import messages
from django.core.paginator import Paginator

PER_PAGE = int(os.environ.get('PER_PAGE', 6))

# Created view home 
def home(request,):
    
    recipe = RecipeModel.objects.filter(is_published=True).order_by('-id')

    page_obj, pagination_range = make_pagination(request, recipe, PER_PAGE)
    return render(request, 'recipes/pages/home.html', context={
        'recipes':page_obj,
        'pagination_range':pagination_range,
})

def category(request, id_category):
    recipe = get_list_or_404(RecipeModel.objects.filter(
        category__id=id_category,
        is_published=True,
    ).order_by('-id') )

    page_obj, pagination_range = make_pagination(request, recipe, PER_PAGE)
    return render(request, 'recipes/pages/category.html', context={
        'recipes': page_obj,
        'pagination_range':pagination_range,
        'title': f'{recipe[0].category.name} - category |',
    })

def recipe(request, id):
   
    recipe = get_object_or_404(RecipeModel, pk = id, is_published = True )

    return render(request, 'recipes/pages/recipe-view.html', context={
        'recipe': recipe,
        'is_detail_page': True,
        
    })

def teste(request):
    return render(request, 'global/base.html')

def search(request):
    search_term = request.GET.get("q", '').strip()
    if not search_term:
        raise Http404()
    
    recipes = RecipeModel.objects.filter(
        Q(
            Q(title__icontains = search_term) |
            Q(description__icontains = search_term),
        ), 
        is_published = True    
    ).order_by('-id')

    page_obj, pagination_range = make_pagination(request, recipes, PER_PAGE)

    return render(request, 'recipes/pages/search.html', {
        'page_title': f'search for "{search_term}" |',
        'search_term': search_term,
        'recipes': page_obj,
        'pagination_range': pagination_range,
        'additional_url_query': f'&q={search_term}',
    })

recipes/templates/recipes/partials/footer.html
<footer class="main-footer">
    <div class="developer">
        <a href="https://www.gustavomiranda.com.br/" target="_blank" rel="noreferrer noopener">By Otávio Miranda</a>
    </div>
    <div class="powered">
        <a href="https://www.djangoproject.com/" target="_blank" rel="noreferrer noopener">Powered by Django!</a>
    </div>
</footer>

recipes/templates/recipes/partials/head.html
{% load static %}
<meta charset="UTF-8">
<meta name="viewport" content="width=device-width, initial-scale=1.0">

<link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/5.15.4/css/fontawesome.min.css"
  integrity="sha512-P9vJUXK+LyvAzj8otTOKzdfF1F3UYVl13+F8Fof8/2QNb8Twd6Vb+VD52I7+87tex9UXxnzPgWA3rH96RExA7A=="
  crossorigin="anonymous" referrerpolicy="no-referrer" />

<link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/5.15.4/css/brands.min.css"
  integrity="sha512-sVSECYdnRMezwuq5uAjKQJEcu2wybeAPjU4VJQ9pCRcCY4pIpIw4YMHIOQ0CypfwHRvdSPbH++dA3O4Hihm/LQ=="
  crossorigin="anonymous" referrerpolicy="no-referrer" />

<link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/5.15.4/css/solid.min.css"
  integrity="sha512-tk4nGrLxft4l30r9ETuejLU0a3d7LwMzj0eXjzc16JQj+5U1IeVoCuGLObRDc3+eQMUcEQY1RIDPGvuA7SNQ2w=="
  crossorigin="anonymous" referrerpolicy="no-referrer" />

<link rel="preconnect" href="https://fonts.googleapis.com">
<link rel="preconnect" href="https://fonts.gstatic.com" crossorigin>
<link href="https://fonts.googleapis.com/css2?family=Roboto+Slab:wght@100..900&display=swap" rel="stylesheet">
<link rel="stylesheet" href="{% static 'recipe/css/style.css' %}">
<link rel="stylesheet" href="{% static '/base_static/css/global-style.css' %}">

recipes/templates/recipes/partials/headers.html
<header class="main-header-container">
    <div class="header container">
        <h1>
            <a class="main-log" href="{% url 'recipes:home' %}"><i class="fas fa-utensils main-logo-icon">

                </i>Recipes</a>
        </h1>
    </div>

</header>

recipes/templates/recipes/partials/messages.html
{% if messages %}
    <div class="main-content center container message-container">
        {% for message in messages %}
            <div class="message {{ message.tags }}">
                {{ message }}
            </div>
        {% endfor %}
    </div>
{% endif %}

recipes/templates/recipes/partials/pagination.html
<div class="container pagination">
    <div class="pagination-content">
      {% if pagination_range.first_page_out_of_range %}
        <a class="page-link page-item" href="?page=1{{ additional_url_query }}">1</a>
        <span class="page-item">...</span>
      {% endif %}

      {% for page in pagination_range.pagination %}
        {% if pagination_range.current_page == page %}
          <a class="page-link page-item page-current" href="?page={{ page }}{{ additional_url_query }}">{{ page }}</a>
        {% else %}
          <a class="page-link page-item" href="?page={{ page }}{{ additional_url_query }}">{{ page }}</a>
        {% endif %}
      {% endfor %}

      {% if pagination_range.last_page_out_of_range %}
        <span class="page-item">...</span>
        <a class="page-link page-item" href="?page={{ pagination_range.total_pages }}{{ additional_url_query }}">{{ pagination_range.total_pages }}</a>
      {% endif %}    
    </div>
  </div>

recipes/templates/recipes/partials/recipe.html
<div class="recipe recipe-list-item">
    <div class="recipe-cover">
        <a href="{% url 'recipes:recipes' recipe.id %}"  >
            <img src="{{recipe.cover.url}}" alt="img via placehold" srcset="">
        </a>
    </div>
    <div class="recipe-title-container">
        <a href="{% url 'recipes:recipes' recipe.id %}">
            <h2 class="recipe-title">{{ recipe.title }}</h2>
        </a>
    </div>

    <div class="recipe-author">
        {% if recipe.author is not None %}
            <span class="recipe-author-item">
                <i class="fas fa-user"></i>
                {% if recipe.author.first_name%}
                {{recipe.author.first_name}}{{recipe.author.last_name}}
                {% else %}
                    {{recipe.author.username}}
                {% endif %}
        {% endif %}
        </span>
        <span class="recipe-author-item">
            <i class="fas fa-calendar-alt"></i>
            16/10/2021 às 11:21
        </span>
        {% if recipe.category is not None %}
            <span class="recipe-author-item">
                <a href="{% url 'recipes:category' recipe.category.id %}">
                    <i class="fas fa-layer-group"></i>
                    <span>{{recipe.category.name}}</span>
                </a>
            </span>
        {% endif %}
    </div>

    <div class="recipe-content">
        <p>{{recipe.description}}</p>
    </div>

    <div class="recipe-meta-container">
        <div class="recipe-meta recipe-preparation">
            <h3 class="recipe-meta-title"><i class="fas fa-stopwatch"></i> Preparo</h3>
            <div class="recipe-meta-text">
                {{recipe.preparation_time}} {{recipe.preparation_time_unit}}
            </div>
        </div>
        <div class="recipe-meta recipe-servings">
            <h3 class="recipe-meta-title"><i class="fas fa-pizza-slice"></i> Porções</h3>
            <div class="recipe-meta-text">
                {{recipe.servings}} {{recipe.servings_unit}}
            </div>
        </div>
    </div>

    {% if is_detail_page is not True %}
    <footer class="recipe-footer">
        <a class="recipe-read-more button button-dark button-full-width" href="{% url 'recipes:recipes' recipe.id  %}">
            <i class="fas fa-eye"></i>
            <span>ver mais...</span>
        </a>
    </footer>
    {% endif %}

    {% if is_detail_page is True%}
    <div class="preparation-steps">
        {% if recipe.preparation_step_is_htm is True %}
            {{recipe.preparation_step | safe}}
        {% else %}
            {{recipe.preparation_step | linebreaksbr}}
        {% endif %}
    </div>
    

    {% endif %}
</div>

recipes/templates/recipes/partials/search.html
<div class="search-container">
    <div class="container">
        <form action="{% url 'recipes:search' %}" metohd="get" class="search-form" >
            <input type="search" class="search-input" name="q" value="{{search_term}}" required>
            <button type="submit" class="search-button" ><i class=" fas fa-search"></i></button>
        </form>
    </div>
</div>