Project/urls.py
from django.conf.urls.static import static
from django.urls import path,include
from django.conf import settings
from django.contrib import admin


urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('recipes.urls')),
    path('author/', include ('authors.urls'))
]

urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)
urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

authors/urls.py
from django.urls import path
from . import views

app_name = "authors"

urlpatterns = [
    path('register/', views.register_view, name="register" ),
    path('register/create/', views.register_create, name="create")
]

authors/models.py
from django.db import models

# Create your models here.

authors/forms.py
import re
from django import forms
from django.core.exceptions import ValidationError
from django.contrib.auth.models import User

def strong_password(password):
    regex = re.compile(r'^(?=.*[a-z])(?=.*[A-Z])(?=[0-9]).{8,}$')
    if not regex.match(password):
        raise ValidationError(
            ('Password must have at letter one uppercase,'
             'one letter lowercase,'
             'one number. the lentgh should be at least 8 characters'),
             code='invalid'
        )
    
def add_attr(field, attr_name, attr_new_val):
    existing_attr = field.widget.attrs.get(attr_name,'')
    field.widget.attrs[attr_name] = f'{existing_attr} {attr_new_val}'.strip()

def add_placeholder(field, placeholder_val):
    add_attr(field,'placeholder', placeholder_val)

class RegisterForm(forms.ModelForm):
    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        add_placeholder(self.fields['first_name'], 'Ex: John')
        add_placeholder(self.fields['last_name'], 'Ex: Doe')
        add_placeholder(self.fields['username'], 'Your username')
        add_placeholder(self.fields['email'], 'Ex: youremail@email.com')
        add_attr(self.fields['first_name'], 'requerid', 'Fisrt_name must not be empty')

    
   
    first_name = forms.CharField(
            error_messages={'required': 'Write yuor first name'},
            label='First name',
            )
    
    last_name = forms.CharField(
            error_messages={'required': 'Write yuor last name',},
            label='Last name',
            )
    
    username = forms.CharField(
        error_messages= {'required':'This field must not be empty',
                        'min_length':'Username must be have at least 4 characters',
                        'max_length': 'Username must have less than 150 characters'},
        label='Username',
        help_text=('Username must have letters, numbers or one be of those @.+-_,'
                   'the length should be  between 4 and 150 characters'),
                   min_length=4 , max_length=150

    )

    email = forms.EmailField(
        error_messages={'required': 'the E-mail must be valid'},
        label='E-mail',
         help_text = 'the E-mail must be valid'
    
    )

    password = forms.CharField(
        required=True,
        widget = forms.PasswordInput(attrs= {'placeholder': 'Your Password'}),
        error_messages= {
            'required' : 'Password must not be empty',
            
        },
        help_text=('Password must have at letter one uppercase,'
                   'one letter lowercase,'
                   'one number. the lentgh should be at least 8 characters'),

        validators = [strong_password],

        label='Password',

        
        
    )

    password2 = forms.CharField(
        required=True,
        widget = forms.PasswordInput(attrs= {'placeholder': 'Repeat your Password'}),
         error_messages= {
            'required' : 'Password must not be empty'
        },

        label='Password2'
    )
    class Meta:
        model = User
        fields = [
            'first_name',
            'last_name',
            'username',
            'email',
            'password',
            'password2'
        ]

           
    def clean(self):
        cleaned_data = super().clean()
        password = cleaned_data.get('password')
        password2 = cleaned_data.get('password2')

        if password != password2:
            password_confirmation_error = ValidationError(
                "Password 1 and Password 2 must be equal",
                code = "invalid")
            raise ValidationError ({
                "password" : password_confirmation_error,
                "password2": [
                    password_confirmation_error
                ]
            })

authors/views.py
from django.shortcuts import render, redirect
from django.http import Http404
from authors.forms import RegisterForm
from django.contrib import messages

# Create your views here.
def register_view(request):

    
    register_form_data = request.session.get('register_form_data', None)
    form = RegisterForm(register_form_data)

    context = {
        'form':form
    }
    return render(request, 'authors/pages/register_view.html', context)

def register_create(request):
    if not request.POST:
        raise Http404()
    
    POST = request.POST
    request.session['register_form_data'] = POST
    form = RegisterForm(POST)

    if form.is_valid():
        form.save()
        messages.success(request, 'Your user is created, please log in.')

        del(request.session['register_form_data'])

    return redirect('authors:register')

authors/templates/authors/pages/register_view.html
{% extends "global/base.html" %}
{% load bootstrap5 %}

{% block title %} Register | {%endblock title%}

{% block content %} 
    <div class="main-content center container">
        <h1>Register</h1>
    </div>
    {% include 'recipes/partials/messages.html' %} 
    <div class="main-content container">
        <form action="{% url 'authors:create' %}" method="POST">{% csrf_token %}
            <div class="form-content form-content-grid">
                {% for field in form %}
                <div class="form-group">
                    <label for="{{field.id_for_label}}">{{field.label}}</label>
                    {{field}}
                    {% if field.help_text %}
                       <p class="help-text">{{field.help_text}}</p>
                    {% endif %}
                    {{field.errors}}
                   
    
                </div>
                {%endfor%}
            </div>
            {% if form.errors %}
            <div class="form-content form-content-grid">
              <div class="form-group">
                <div class="message message-error">
                  There are errors in the form, please fix them and send again.
                </div>
              </div>
            </div>
            {% endif %}
            <div class="form-content form-content-grid">
                <div class="form-group">  
                    <button type="submit">Send</button>
                </div>
            </div>
        </form>
    </div>
{% endblock content %}